# Statistic routes
statistic_routes:
    resource: "@FreeBetStatisticBundle/Resources/config/routing.yml"

# User routes
user_routes:
    resource: "@FreeBetUserBundle/Resources/config/routing.yml"

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
        _locale: en|fr|es

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: en|fr|es

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: en|fr|es

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Event routes
event_routes:
    resource: "@FreeBetCompetitionBundle/Resources/config/routing.yml"

# Cart routes
cart_routes:
    resource: "@FreeBetGambleBundle/Resources/config/routing_cart.yml"
    prefix: /cart

# Cart routes
gamble_routes:
    resource: "@FreeBetGambleBundle/Resources/config/routing_gamble.yml"
    prefix: /gamble